# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 314fb8fc38c926a152a164f36f5f98d1b14b1246b157bd7720abb85772cf208185e2d8c8375e136b290323bd6bb586c1668ff5ba0c81013726804e2b92818d76

test:
  secret_key_base: fd70938fd1dd1ab0846147e692141914ea3a6dc6d815a0e9403ffff9336203827bb369325fda5f58277a6da0b50df88381a1e0e7b589c21f7837e869e64fd604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
